INSERT INTO USUARIOS(ID, NOME, USUARIO, EMAIL) VALUES(1, "ALEXSANDER", "LEXIPEDIA", "ALEXSANDER.MVIANA@GMAIL.COM");
INSERT INTO USUARIOS(ID, NOME, USUARIO, EMAIL) VALUES(2, "FULANINHO", "FULANOPEDIA", "FULANO.MVIANA@GMAIL.COM");
INSERT INTO USUARIOS(ID, NOME, USUARIO, EMAIL) VALUES(3, "CICLANO", "CICLANOPEDIA", "CICLANO.MVIANA@GMAIL.COM");
INSERT INTO USUARIOS(ID, NOME, USUARIO, EMAIL) VALUES(4, "BELTRANO", "BELTRANOPEDIA", "BELTRANO.MVIANA@GMAIL.COM");